import Products from '@/components/home/Products';
import React from 'react';



export const metadata = {
    title: "All Products",
    description: "Generated by create next app"
}


const ProductsPage = async () => {

     await new Promise(res => setTimeout(res, 2000));
    
    return (
        <div>
            <Products></Products>
        </div>
    );
};

export default ProductsPage;






// import Products from '@/components/home/Products';

// export default async function Page() {
//   // simulate API delay
//   await new Promise(res => setTimeout(res, 2000));

//   return (
//     <div>
//       <Products />
//     </div>
//   );
// }




